version: '1.0'
services:
  mongo:
    container_name: mongodb
    restart: always
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017

  app:
    build: .
    container_name: app
    restart: always
    env_file:
      - ./.env.docker
    ports:
      - 2022:2022
    depends_on:
      - mongo

#  backend:
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    container_name: 'backend'
#    env_file:
#      - ./.env
#    restart: 'always'
#    depends_on:
#      - mongo
#    ports:
#      - '2022:2022'